### ISSUE TITLE
Callback after Transition

### ISSUE THREAD

**Issue by taras** [cowboyd/microstates.js#17]
When we start integrating microstates into Ember helpers, we'll need the helper to know when a transition occurred so it'll trigger `recompute` on the helper. We need the microstate to notify us of a transition.

What if a microstate constructor received a second argument which would accept a callback? After the transition, we'll call the callback and pass new microstate as an argument.

I created a gist to show what different ember-microstate helpers might look like with this pattern. https://gist.github.com/taras/48839269bcda7ffc44d098c1b5f1bee2

Thoughts?

**Comment by cowboyd** [comment]
The microstates themselves are immutable data structures and the transitions themselves pure functions that are guaranteed to never have any side-effects. 

However, based on the metadata of the microstate, we should be able to generate an ES7 Observable that can wrap _any_ microstate, its transitions and emit a new state whenever it changes.

```js
import { ObservableState } from 'microstates';
import { List } from 'microstates';

let observable = new ObservableState(new List());

observable.subscribe(state => console.log('new state is ', state));

observable.map(state => state.length).filter(length => length > 1).subscribe(function() {
  console.log('the list length is 2 or greater')
});

observable.add('one');
//$ new state is ['one']
observable.add('two');
//$ new state is ['one', 'two']
//$ the list is length 2 or greater
observable.clear();
//$ new state is []

```

For the record, if we can generate an observable, we should also be able to generate a redux container and/or a set of redux reducers that automatically manipulate the microstate.
