### ISSUE TITLE
String transitions

### ISSUE THREAD

**Issue by taras** [cowboyd/microstates.js#27]
We currently only support `concat` transition on String type. 

Vote for which transitions we should support.

**Comment by taras** [comment]
- [ ] [padEnd](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd)

**Comment by taras** [comment]
[repeat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat)

**Comment by taras** [comment]
[replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace)

**Comment by taras** [comment]
[slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice)

**Comment by taras** [comment]
[substring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr)

**Comment by taras** [comment]
[toLowerCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase) and [toUpperCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase)

**Comment by taras** [comment]
[trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim)

**Comment by sivakumar-kailasam** [comment]
@taras  Why is this closed?
