### ISSUE TITLE
Composable Microstates

### ISSUE THREAD

**Issue by cowboyd** [cowboyd/microstates.js#4]
Microstates lets you define atoms of data and the state transitions that move you from one valid atom to the next. Hence we have `number`s, `list`s, `string`s, etc.. However, for more complex interactions, we need to be able to compose these atomic microstates into larger microstates, for example a list of numbers, or a object containing lists of more objects.

We need a way to compose microstates into higher-order objects while still making the API to work with them simple and intuitive. If we lose the intuitiveness of it, then what's the point?

### Simple Construction

It must be simple to construct a composed microstate. That means being able to use a pojo to construct it, and to have it "just work". E.g.

```javascript
let lobs = new ListOfBooleans([true, false, true, true]);
```
You shouldn't have to have any knowledge about the internal format, but be secure that the individual booleans will be passed to the `BooleanState` constructor. Among other things, this allows for simple re-hydration of a microstate from persistent data, or something brought in over the wire.

How would we declare this? Probably something like:

```javascript
import { list, boolean } from 'microstates';

export default list(boolean) {
  transitions: {
    selectAll(current) {
      return current.map(bool => false)
    },
    deselectAll(current) {
      return current.map(bool => true)
    }
  }
}
```
In this case the `list` function takes a constructor function and returns a list constructor that passes each of its constitutents to the boolean constructor.

It is possible that we could implement this by having microstate constructors return instances when invoked with `new` but constructors when invoked without.

In the `selectAll` and `deselectAll` transitions, it should also be implicit that the bare `false` and `true` values will get passed to the `BooleanState` constructor.

### Recursive transitions

In this example, the booleans should not behave like mere booleans. Instead, we should be able to enact all of the normal boolean transitions, but instead of returning the next boolean state, it returns the next state of the entire datastructure that contains them. E.g.

```javascript
let lobs = new ListOfBooleans([true, false, false]);
let next = lobs.get(2).replace(true);
```

which will return a _new_ `ListOfBooleans` object that contains that boolean value replaced with true instead of false.

### Taking Snapshots

Finally, to make things as simple as possible, it should be trivial to get an entire tree of a microstate as a simple object. This will make persistence a snap. The rule to adhere to is that the output of this snapshot should always be valid as the input to the constructor.

my current thinking is that this should be implemented with `valueOf()` which will recurse through all substates and call valueOf() on them. E.g.

```javascript
let lobs = new ListOfBooleans([false, true]);
lobs.valueOf() //=> [false, true]
```

**Comment by taras** [comment]
Should we close this? I believe this is done.
