### ISSUE TITLE
Boolean State

### ISSUE THREAD

**Issue by cowboyd** [cowboyd/microstates.js#8]
The microstate primitive `Bool` wraps a simple boolean value.

No matter what you pass to the constructor, it is naturally coerced into a boolean value:

``` js
new Bool(true).valueOf() //=> true
new Bool(false).valueOf() //=> false
new Bool("Ohai") //=> true
new Bool(null) //=> false
```

The same applies if you set a boolean value to explicit value:

``` js
new Bool(false).set("Ohai").valueOf() //=> true
new Bool(true).set(null).valueOf() //=> false
```

The only other transition available on a boolean value is `toggle`:

``` js
new Bool(true).toggle().valueOf() //=> false
new Bool(false).toggle().valueOf() //=> true
```

**Comment by taras** [comment]
@cowboyd for `new Bool(false).set("Ohai").valueOf()`, does the value become `Ohai` or is it coerced to a boolean at creation?

**Comment by cowboyd** [comment]
You've pointed to an important use-case

```
new Bool(false).set("Ohai").valueOf() //=> true
```

It will be coerced in the sense that all values passed to `set` are passed as arguments to the "constructor" function. Don't know what the syntax will be yet, but probably:

```js
const Bool = State.extend({
  construct(value) {
    return !!value;
  }
});

**Comment by taras** [comment]
you mean, `constructor(value) { return !!value; }` right? 

I tried to implement Bool but it doesn't seem to call the constructor function yet. Is there something missing from implementation to do this yet?

**Comment by cowboyd** [comment]
Yes, it has not been added yet, so you will have to coerce the value manually for now. We could call it `constructor`, but I am a bit worried that it might be confused as the es6 constructor, and it does need a return value.

**Comment by cowboyd** [comment]
`initialize()`, `box()`, `coerce()` might be other options.
